#!/usr/bin/env node

/**
 * Xray Upload Script
 * 
 * Usage: node utils/xray-upload.js
 * 
 * This script:
 * 1. Reads results.xml generated by Playwright JUnit reporter
 * 2. Authenticates with Xray Cloud
 * 3. Uploads the results for traceability in Jira
 * 
 * Environment variables required:
 * - XRAY_CLIENT_ID
 * - XRAY_CLIENT_SECRET
 */

import dotenv from 'dotenv';
dotenv.config();

import { XrayClient } from './XrayClient.js';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const resultsFilePath = join(__dirname, '../results.xml');

async function uploadToXray() {
  try {
    // Check if results file exists
    if (!fs.existsSync(resultsFilePath)) {
      console.warn(
        `⚠️  results.xml not found at ${resultsFilePath}. Skipping Xray upload.`
      );
      process.exit(0);
    }

    // Initialize Xray client
    const xray = new XrayClient();

    // Upload results
    const uploadResponse = await xray.uploadResults(resultsFilePath);

    console.log('\n✅ Upload completed successfully');
    console.log(`Execution details: ${JSON.stringify(uploadResponse, null, 2)}`);
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Upload failed');
    console.error(error.message);
    process.exit(1);
  }
}

// Run upload
uploadToXray();
